version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Build.Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/fastrep_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    volumes:
      - ./resources/static:/app/static  # Подключаем статические файлы
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastrep_db
    ports:
      - "5434:5432"
    networks:
      - app-network
    expose:
      - "5432"
  frontend:
    image: aliquamsiderea/wrapper-front
    ports:
      - "8082:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
